// This file is generated by Slice Machine. Update with care!

import Document from './Document';
import Teste2 from './Teste2';
import TesteSlice from './TesteSlice';

export {
	Document,
	Teste2,
	TesteSlice,
};

export const components = {
	document: Document,
	teste2: Teste2,
	teste_slice: TesteSlice,
};
